baseURL: http://examplesite.org/
title: Bigspring Hugo
theme: bigspring-hugo-startup-theme
languageName: En
languageCode: en-us
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  author: Themefisher
  contact_form_action: '#'
  copyright: Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)
  description: This is meta description
  footer_content: Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique
    eget amet, tempus eu at cttur.
  footer_menu_left: Company
  footer_menu_middle: Product
  footer_menu_right: Support
  logo: images/logo.png
  logo_width: 200px
  navigation_button:
    enable: yes
    label: Get Started
    link: contact
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/slick/slick.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
  preloader:
    enable: no
    preloader: ''
  social:
    - icon: ti-facebook
      link: '#'
      title: facebook
    - icon: ti-twitter-alt
      link: '#'
      title: twitter
    - icon: ti-skype
      link: '#'
      title: skype
    - icon: ti-linkedin
      link: '#'
      title: linkedin
menu:
  footer_left:
    - URL: '#'
      name: About Us
    - URL: '#'
      name: Quick Start
    - URL: pricing
      name: Pricing
  footer_middle:
    - URL: pricing
      name: Pricing
    - URL: '#'
      name: Platform
    - URL: '#'
      name: Features
  footer_right:
    - URL: privacy-policy
      name: Privacy Policy
    - URL: terms-conditions
      name: Terms & Conditions
    - URL: faq
      name: FAQ
  main:
    - URL: blog
      name: Blog
      weight: 1
    - URL: pricing
      name: Pricing
      weight: 2
    - URL: contact
      name: Contact
      weight: 3
    - URL: faq
      name: FAQ
      weight: 4
